# Generated by Django 5.0.7 on 2025-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('linkedin_profile', models.URLField()),
                ('personal_email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='AlumniFounder',
        ),
    ]
